# Generated by Django 3.2.7 on 2021-09-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time_of_event',
        ),
    ]
