# Generated by Django 3.2.7 on 2021-09-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0002_remove_event_time_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.TextField(default=''),
        ),
    ]
